config/routes.rb
Passeme::Application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  match '/demo', to: 'demo#login', via: 'get', as: 'demo'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users
  resources :tasks do
    member do
      put 'toggle_done'
    end
    collection do
      get 'list_all'
      get 'list_pending'
      get 'list_done'
      get 'list_overdue'
    end
  end

  resources :notifications
  resources :groups
  resources :settings do
    member do
      put 'toggle_make_tour_on_login'
    end
  end
  resources :subjects do
    get 'study_sources'
    patch 'study_sources', to: 'subjects#update_study_sources'
    patch 'update_subject_group'
  end

  resources :study_sources
  resources :timetables do
    put 'make_active'
    get 'follow_up', to: 'follow_up#index'
    get 'follow_up/refresh_content', to: 'follow_up#refresh_content'
    get 'reports', to: 'reports#index'
  end
  get 'follow_up', to: 'follow_up#index_active_timetable'
  get 'reports', to: 'reports#index_active_timetable'
  get 'change_timetable_report', to: 'reports#change_timetable'
  resources :calendars do
    resources :calendar_events do
      get 'edit_complete'
      put 'complete'
      put 'info_net_hours'
    end
    resources :calendar_event_sources, as: 'event_sources'
    get 'get_study_sources_for_event_source', to: 'calendar_event_sources#get_study_sources'

    get 'event_instances', to: "event_instances#index"
    post 'day_click'
    post 'event_click'
    post 'select'
  end

  resources :subject_groups

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  match '/about', to: 'static_pages#about', via: 'get', as: 'about'

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  done       :boolean          default(FALSE)
#  due_in     :date
#  user_id    :integer          not null
#

class Task < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }

  belongs_to :user
  validates :name, :user, presence: true
  validates :due_in, allow_nil: true, allow_blank: true, timeliness: { after: Date.current }

  has_many :notifications, as: :object, dependent: :destroy

  def toggle_done!
    self.toggle!(:done)
  end

end

app/controllers/tasks_controller.rb
class TasksController < AuthenticatedController
  include TasksHelper

  before_filter :check_user_is_owner, :only => [:toggle_done, :update, :destroy]

  respond_to :js

  def new
    @task = Task.new
  end

  def update
    @task.update_attributes(task_params)
    load_tasks_count
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save!
    else
      #TODO error
      #render :index
    end
    @tasks = current_user.tasks
  end

  def destroy
    @task.destroy!
    load_tasks_count
  end

  def list_all
    @tasks = current_user.tasks
    render action: 'list'
  end

  def list_pending
    @tasks = current_user.pending_tasks
    render action: 'list'
  end

  def list_done
    @tasks = current_user.done_tasks
    render action: 'list'
  end

  def list_overdue
    @tasks = current_user.overdue_tasks
    render action: 'list'
  end

  def toggle_done
    @task.toggle_done!
    load_tasks_count
  end


  private

  def task_params
    params.require(:task).permit(:name, :due_in)
  end

  def check_user_is_owner
    @task = current_user.tasks.find_by_id(params[:id])
    if @task.nil?
      redirect_to tasks_path
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def load_tasks_count
    @all_tasks_count = current_user.tasks.count
    @pending_tasks_count = current_user.pending_tasks.count
    @done_tasks_count = current_user.done_tasks.count
    @overdue_tasks_count = current_user.overdue_tasks.count
  end

  def formatted(due_in)
    if due_in.nil?
      I18n.t ('tasks.no_due_in')
    else
      I18n.l due_in
    end
  end

end

app/views/tasks/_form_modal.html.erb
<%= simple_form_for @task,
  defaults: { input_html: { class: "m-wrap placeholder-no-fix", autocomplete: "off" } },
  html: { id: 'task-form', class: "form-vertical", novalidate: "novalidate" } do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h3><%= t('.title') %></h3>
  </div>
  <div class="modal-body">
    <div class="alert alert-error hide">
      <button class="close" data-dismiss="alert"></button>
      <%= t('simple_form.error_notification.default_message') %>
    </div>

    <%= f.input :name %>
    <%= f.input :due_in, as: :date_picker %>

  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn"><%= t('buttons.close') %></button>
    <button type="submit" class="btn green"><%= t('buttons.ok') %></button>
  </div>
<% end %>

app/views/tasks/_index.html.erb
<div class="portlet box green tasks-widget">
  <div class="portlet-title">
    <div class="caption"><i class="icon-check"></i><%= t('.title') %></div>
    <div class="tools">
      <a href="" class="collapse"></a>
    </div>
    <div class="actions">
      <div class="btn-group">
        <a class="btn mini" href="#" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
          <%= t('.more_options') %>
          <i class="icon-angle-down"></i>
        </a>
        <ul class="dropdown-menu pull-right">
          <li>
          <%= link_to list_all_tasks_path, class: "list-tasks" do %>
            <i class="i"></i> <%= t('.list.all') %> <span id="all-tasks-count" class="badge"><%= @all_tasks_count %></span>
          <% end %>
          </li>
          <li class="divider"></li>
          <li>
          <%= link_to list_pending_tasks_path, class: "list-tasks" do %>
            <%= t('.list.pending') %> <span id="pending-tasks-count" class="badge badge-important"><%= @pending_tasks_count %></span>
          <% end %>
          </li>

          <li>
          <%= link_to list_overdue_tasks_path, class: "list-tasks" do %>
            <%= t('.list.overdue') %> <span id="overdue-tasks-count" class="badge badge-warning"><%= @overdue_tasks_count %></span> 
          <% end %>
          </li>

          <li>
          <%= link_to list_done_tasks_path, class: "list-tasks" do %>
            <%= t('.list.completed') %> <span id="done-tasks-count" class="badge badge-success"><%= @done_tasks_count %></span> 
          <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="portlet-body">
    <div class="task-content">
      <div class="scroller" style="height: 305px;" data-always-visible="1" data-rail-visible1="1">
        <!-- START TASK LIST -->
        <ul class="task-list unstyled">
          <%= render @tasks %>
        </ul>
        <!-- END START TASK LIST -->
      </div>
    </div>
    <div class="task-footer">
      <span class="pull-right">
        <%= link_to new_task_path, id: "create-task" do %>
          <%= t('.new_task') %> <i class="icon-plus"></i> &nbsp;
        <% end %>
      </span>
    </div>
  </div>
</div>

<div id="task-modal" class="modal hide fade" tabindex="-1">
</div>

app/views/tasks/_task.html.erb
<li id="<%= "task-#{task.id}" %>" class="<%= 'task-done' if task.done? %>"> 
<div class="task-checkbox">
  <%= check_box_tag :done, 1, task.done?, { class: "liChild", data: { url: toggle_done_task_path(task) } } %>
</div>
<div class="task-title">
  <span ></span>
  <a href="#" class="task-title-sp" data-type="text" data-pk="1" data-placement="right" data-placeholder="Required" >
    <%= task.name %>
  </a>

  <span class="task-bell tooltips" data-original-title="<%= formatted task.due_in %>" data-placement="right">
    <a href="#" class="due-date" data-container="body" data-type="date" data-pk="1" data-viewformat="dd/mm/yyyy" data-placement="right" data-original-title="<%= t 'activerecord.attributes.task.due_in' %>" >
      <i class="icon-bell"></i>
    </a>
  </span>
</div>
<div class="task-config">
  <div class="task-config-btn btn-group">
    <a class="btn mini blue" href="#" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"><%= t('.more_options') %> <i class="icon-angle-down"></i></a>
    <ul class="dropdown-menu pull-right">
      <li>
      <%= link_to task, class: "delete-task" do %>
        <i class="icon-trash"></i> <%= t('.delete_task') %>
      <% end %>
      </li>
    </ul>
  </div>
</div>
</li>

app/views/tasks/create.js.erb
<%= render template: 'tasks/list' %>
$('#task-modal').modal('hide');
Tasks.updateDashboardWidget();

app/views/tasks/destroy.js.erb
$('li#task-<%= @task.id %>').remove();
$('#all-tasks-count').text('<%= @all_tasks_count %>');
$('#pending-tasks-count').text('<%= @pending_tasks_count %>');
$('#done-tasks-count').text('<%= @done_tasks_count %>');

app/views/tasks/list.js.erb
$(".task-list").html("<%= j render @tasks %>")

app/views/tasks/new.js.erb
$('#task-modal').html("<%= j render 'form_modal' %>");
$('#task-modal').modal("show");

app/views/tasks/toggle_done.js.erb
$('li#task-<%= @task.id %>').toggleClass("task-done");
$('#pending-tasks-count').text('<%= @pending_tasks_count %>');
$('#done-tasks-count').text('<%= @done_tasks_count %>');
$('#overdue-tasks-count').text('<%= @overdue_tasks_count %>');

app/views/tasks/update.js.erb
$('#overdue-tasks-count').text('<%= @overdue_tasks_count %>');