config/routes.rb
Passeme::Application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  match '/demo', to: 'demo#login', via: 'get', as: 'demo'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users
  resources :tasks do
    member do
      put 'toggle_done'
    end
    collection do
      get 'list_all'
      get 'list_pending'
      get 'list_done'
      get 'list_overdue'
    end
  end

  resources :notifications
  resources :groups
  resources :settings do
    member do
      put 'toggle_make_tour_on_login'
    end
  end
  resources :subjects do
    get 'study_sources'
    patch 'study_sources', to: 'subjects#update_study_sources'
    patch 'update_subject_group'
  end

  resources :study_sources
  resources :timetables do
    put 'make_active'
    get 'follow_up', to: 'follow_up#index'
    get 'follow_up/refresh_content', to: 'follow_up#refresh_content'
    get 'reports', to: 'reports#index'
  end
  get 'follow_up', to: 'follow_up#index_active_timetable'
  get 'reports', to: 'reports#index_active_timetable'
  get 'change_timetable_report', to: 'reports#change_timetable'
  resources :calendars do
    resources :calendar_events do
      get 'edit_complete'
      put 'complete'
      put 'info_net_hours'
    end
    resources :calendar_event_sources, as: 'event_sources'
    get 'get_study_sources_for_event_source', to: 'calendar_event_sources#get_study_sources'

    get 'event_instances', to: "event_instances#index"
    post 'day_click'
    post 'event_click'
    post 'select'
  end

  resources :subject_groups

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  match '/about', to: 'static_pages#about', via: 'get', as: 'about'

end

app/models/calendar_event_source.rb
# == Schema Information
#
# Table name: calendar_event_sources
#
#  id          :integer          not null, primary key
#  subject_id  :integer          not null
#  color       :string(255)      not null
#  created_at  :datetime
#  updated_at  :datetime
#  calendar_id :integer          not null
#

class CalendarEventSource < ActiveRecord::Base

  default_scope { includes(:subject, :calendar) }

  belongs_to :calendar
  belongs_to :subject
  has_many :calendar_events

  accepts_nested_attributes_for :calendar_events, allow_destroy: true

  validates :subject, :color, presence: true

  validates_associated :calendar_events

  def name
    subject.name
  end
end

app/controllers/calendar_event_sources_controller.rb
class CalendarEventSourcesController < AuthenticatedController
  before_filter :check_user_is_owner_of_calendar
  before_filter :check_user_is_owner_of_event_source, :only => [:edit, :update, :destroy, :get_study_sources ]

  add_breadcrumb I18n.t('calendar_event_sources.breadcrumb'), :calendar_event_sources_path

  def index
    @event_sources = @calendar.calendar_event_sources
  end

  def create
    @event_source = @calendar.calendar_event_sources.build(event_source_params)
    if @event_source.save!
      flash[:notice] = t('.create_successful')
    else
      #TODO error
      #render :index
    end

    respond_to do |format|
      format.html { redirect_to action: :index }
      format.js
    end
  end

  def new
    @event_source = CalendarEventSource.new
    @subjects = current_user.subjects.not_in_calendar(@calendar)
  end

  def edit
    @subjects = current_user.subjects
  end

  def update
    flash[:notice] = t('.update_successful') if @event_source.update_attributes(event_source_params)
    redirect_to action: :index
  end

  def destroy
    @event_source.destroy!
    render nothing: true
  end

  def get_study_sources
    respond_to do |format|
      format.js { render json: @event_source.subject.study_sources, only: [:id, :title] }
    end
  end


  private

  def event_source_params
    params.require(:calendar_event_source).permit(:subject_id, :color, :author)
  end

  def check_user_is_owner_of_calendar
    @calendar = Calendar.find_by_id(params[:calendar_id])
    if @calendar.blank? || @calendar.timetable.creator != current_user
      redirect_to root_path
    end
  end

  def check_user_is_owner_of_event_source
    @event_source = @calendar.calendar_event_sources.find_by_id(params[:id])
    if @event_source.nil?
      redirect_to calendar_event_sources_path
    end
  end
end

app/views/calendar_event_sources/_form_modal.html.erb
<%= simple_form_for [@calendar, @event_source],
  url: @event_source.persisted? ? calendar_event_source_path : calendar_event_sources_path,
  defaults: { input_html: { class: "m-wrap placeholder-no-fix", autocomplete: "off" } },
  html: { id: 'event-source-form', class: "form-vertical", novalidate: "novalidate" } do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h3><%= t('.title') %></h3>
  </div>
  <div class="modal-body">
    <div class="alert alert-error hide">
      <button class="close" data-dismiss="alert"></button>
      <%= t('simple_form.error_notification.default_message') %>
    </div>
    <div class="row-fluid">
      <div class="span8">
        <%= f.association :subject, collection: @subjects %>
      </div>
      <div class="span4">
        <%= f.input :color, as: :simple_color_picker %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn"><%= t('buttons.close') %></button>
    <button type="submit" class="btn green"><%= t('buttons.ok') %></button>
  </div>
<% end %>

app/views/calendar_event_sources/create.js.erb
$('#event-source-modal').modal('hide');

app/views/calendar_event_sources/edit.js.erb
$('#event-source-modal').html("<%= j render 'form_modal' %>");
$('#event-source-modal').modal('show');

EventSources.initFormValidation();

app/views/calendar_event_sources/index.html.erb
<% provide(:title, t('.title')) %>



<div class="table-toolbar">
  <div class="btn-group">
    <%= button_to new_calendar_event_source_path(@calendar), class: "btn green", id: "new-event-source" do %>
      <%= t('buttons.add') %> <i class="icon-plus"></i>
    <% end %>
  </div>
</div>
<table class="table table-striped table-bordered table-hover" id="table-event-sources">
  <thead>
    <tr>
      <th><%= t('.table_label.subject') %></th>
      <th><%= t('.table_label.color') %></th>
      <th><%= t('.table_label.edit') %></th>
      <th><%= t('.table_label.delete') %></th>
    </tr>
  </thead>
  <tbody>
    <% @event_sources.each do |s| %>
      <tr class="odd gradeX">
        <td class="text-center"><%= s.subject.name %></td>
        <td class="text-center">
          <span class="simplecolorpicker">
            <span style="background-color: <%= s.color %>;" class="color"></span>
          </span>
        </td>
        <td class="text-center">
          <%= button_to edit_calendar_event_source_path(@calendar, s), class: 'btn blue edit' do %>
            <i class="icon-pencil"></i>
          <% end %>
        <td class="text-center">
          <%= button_to calendar_event_source_path(@calendar, s), class: 'btn red delete' do %>
            <i class="icon-remove"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="event-source-modal" class="modal hide fade" tabindex="-1">
</div>

app/views/calendar_event_sources/new.js.erb
$('#event-source-modal').html("<%= j render 'form_modal' %>");
$('#event-source-modal').modal('show');

EventSources.initFormValidation();