config/routes.rb
Passeme::Application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  match '/demo', to: 'demo#login', via: 'get', as: 'demo'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users
  resources :tasks do
    member do
      put 'toggle_done'
    end
    collection do
      get 'list_all'
      get 'list_pending'
      get 'list_done'
      get 'list_overdue'
    end
  end

  resources :notifications
  resources :groups
  resources :settings do
    member do
      put 'toggle_make_tour_on_login'
    end
  end
  resources :subjects do
    get 'study_sources'
    patch 'study_sources', to: 'subjects#update_study_sources'
    patch 'update_subject_group'
  end

  resources :study_sources
  resources :timetables do
    put 'make_active'
    get 'follow_up', to: 'follow_up#index'
    get 'follow_up/refresh_content', to: 'follow_up#refresh_content'
    get 'reports', to: 'reports#index'
  end
  get 'follow_up', to: 'follow_up#index_active_timetable'
  get 'reports', to: 'reports#index_active_timetable'
  get 'change_timetable_report', to: 'reports#change_timetable'
  resources :calendars do
    resources :calendar_events do
      get 'edit_complete'
      put 'complete'
      put 'info_net_hours'
    end
    resources :calendar_event_sources, as: 'event_sources'
    get 'get_study_sources_for_event_source', to: 'calendar_event_sources#get_study_sources'

    get 'event_instances', to: "event_instances#index"
    post 'day_click'
    post 'event_click'
    post 'select'
  end

  resources :subject_groups

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  match '/about', to: 'static_pages#about', via: 'get', as: 'about'

end

app/models/subject_group.rb
# == Schema Information
#
# Table name: subject_groups
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class SubjectGroup < ActiveRecord::Base


  has_many :subjects, dependent: :nullify
  belongs_to :user

  validates :name, :user, presence: true

  def subjects_with_study_sources
    subjects.merge(Subject.with_study_sources)
  end

end

app/controllers/subject_groups_controller.rb
class SubjectGroupsController < AuthenticatedController

  add_breadcrumb I18n.t('subject_groups.breadcrumb'), :subject_groups_path

  before_filter :check_user_is_owner_of_subject_group, :only => [:update, :destroy ]
  
  def index
    @subjects = current_user.subjects.where(subject_group_id: nil)
    @subject_groups = current_user.subject_groups.includes(:subjects)
    @subject_group = SubjectGroup.new
  end

  def create
    @subject_group = current_user.subject_groups.build(subject_group_params)
    if @subject_group
      update_subjects(params[:subject_ids], @subject_group)
      @subject_group.save!

    else
    #TODO error
    #render :index
    end
  end

  def update
    @subject_group.update_attributes(subject_group_params)
    update_subjects(params[:subject_ids], @subject_group)
  end

  def destroy
    @subject_group.destroy!
    render nothing: true
  end
  
  private

  def update_subjects(ids, subject_group)
    if ids.present?
      ids.each do |i|
        #TODO only the subjects he owns
        #Subject.find_by_id(i).update_attribute(:subject_group, subject_group)
        subject_group.subjects << Subject.find_by_id(i)
      end
    end
  end

  def subject_group_params
    params.require(:subject_group).permit(:name, subject_ids: [])
  end

  def check_user_is_owner_of_subject_group
    @subject_group = current_user.subject_groups.find_by_id(params[:id])
    if @subject_group.nil?
      redirect_to subject_groups_path
    end
  end

end

app/views/subject_groups/_subject.html.erb
<li>
	<input type="hidden" class="subject-id" name="subject_ids[]" value="<%= s.id %>" />
  <input type="hidden" class="subject-update-url" value="<%=  subject_update_subject_group_path(s) %>">
  <%= s.name %>
</li>

app/views/subject_groups/_subject_group.html.erb
<div class="portlet box grey subject-group-box">
  <input type="hidden" class="subject-group-id" value="<%= sg.id %>">

  <div class="portlet-title">
    <div class="caption"><%= sg.name %></div>
    <div class="tools">
      <a href="javascript:;" class="collapse"></a>
      <%= link_to '', subject_group_path(sg), class: "remove" %>
    </div>
  </div>

  <div class="portlet-body">
    <ul class="sortable-itens <%='sortable-box-placeholder empty' if sg.subjects.empty? %>">
      <%= render partial: 'subject', collection: sg.subjects, as: :s %>
    </ul>
  </div>

</div>

app/views/subject_groups/create.js.erb
$('#new-subjects').empty();
$('#new-subjects').addClass('sortable-itens sortable-box-placeholder empty');
$('#subject_group_name').val('');


//Add na lista de subject groups
$('#subject-groups').prepend('<%= j render "subject_group", sg: @subject_group %>')

app/views/subject_groups/destroy.js.erb
var $box = $('.subject-group-id[value=<%= @subject_group.id %>]').closest('.subject-group-box');

$box.find('.sortable-itens > li').each(function(index, ele){
  $('#available-subjects').append($(ele));
});
$box.hide(); //hiding instead of removing so the ajax callback can be completed

app/views/subject_groups/index.html.erb
<% provide(:title, t(".title")) %>


<div class="span3 column sortable">
  <div class="portlet box yellow" id="available-subjects-box">
    <div class="portlet-title">
      <div class="caption"><%= t('.available_subjects') %></div>
      <div class="tools">
        <a href="javascript:;" class="collapse"></a>
      </div>
    </div>

    <div class="portlet-body">

      <ul id="available-subjects" class="sortable-itens <%='sortable-box-placeholder empty' if @subjects.empty? %>">
        <%= render partial: 'subject', collection: @subjects, as: :s %>
      </ul>

    </div>

  </div>
</div>
<div class="span6 column sortable">
  <div class="portlet box green" id="new-subject-group-box">
    <div class="portlet-title">
      <div class="caption"><%= t('.new_group') %></div>
      <div class="tools">
        <a href="javascript:;" class="collapse"></a>
      </div>
    </div>
    <div class="portlet-body">
      <%= simple_form_for(@subject_group, remote: true,
                          html: { method: :post, id: "new-subject-group", class: "form-inline subject-group-form" },
                          defaults: { input_html: { class: "m-wrap placeholder-no-fix span8", autocomplete: "off" } }) do |f| %>

        <%= f.input_field :name, label: false %>
        <%= submit_button t("buttons.submit")  %>

      
	      <div class="separator"></div>
	      <ul id="new-subjects" class="sortable-itens sortable-box-placeholder empty">
	      </ul>
      <% end %>
    </div>
  </div>
</div>

<div id="subject-groups" class="span3 column sortable">
  <%= render partial: 'subject_group', collection: @subject_groups, as: :sg %>
</div>