config/routes.rb
Passeme::Application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  match '/demo', to: 'demo#login', via: 'get', as: 'demo'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users
  resources :tasks do
    member do
      put 'toggle_done'
    end
    collection do
      get 'list_all'
      get 'list_pending'
      get 'list_done'
      get 'list_overdue'
    end
  end

  resources :notifications
  resources :groups
  resources :settings do
    member do
      put 'toggle_make_tour_on_login'
    end
  end
  resources :subjects do
    get 'study_sources'
    patch 'study_sources', to: 'subjects#update_study_sources'
    patch 'update_subject_group'
  end

  resources :study_sources
  resources :timetables do
    put 'make_active'
    get 'follow_up', to: 'follow_up#index'
    get 'follow_up/refresh_content', to: 'follow_up#refresh_content'
    get 'reports', to: 'reports#index'
  end
  get 'follow_up', to: 'follow_up#index_active_timetable'
  get 'reports', to: 'reports#index_active_timetable'
  get 'change_timetable_report', to: 'reports#change_timetable'
  resources :calendars do
    resources :calendar_events do
      get 'edit_complete'
      put 'complete'
      put 'info_net_hours'
    end
    resources :calendar_event_sources, as: 'event_sources'
    get 'get_study_sources_for_event_source', to: 'calendar_event_sources#get_study_sources'

    get 'event_instances', to: "event_instances#index"
    post 'day_click'
    post 'event_click'
    post 'select'
  end

  resources :subject_groups

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  match '/about', to: 'static_pages#about', via: 'get', as: 'about'

end

app/controllers/reports_controller.rb
class ReportsController < AuthenticatedController
  before_filter :check_user_is_owner_of_timetable, except: [ :index_active_timetable ]

  add_breadcrumb I18n.t('reports.breadcrumb'), :reports_path

  def index
  end

  def index_active_timetable
    @timetable = current_user.timetables.where(active: true)[0]
    if @timetable.blank?
      render 'timetables/no_timetable'
    else
      render :index
    end
  end

  def change_timetable
    reports = Reports.new(@timetable).generate_all
    respond_to do |format|
      format.json { render json: reports.to_json }
    end
  end

  private

  def check_user_is_owner_of_timetable
    @timetable = current_user.timetables.find_by_id(params[:timetable_id])
    if @timetable.nil?
      redirect_to timetables_path
    end
  end
end

app/views/reports/_expected_and_accomplished.html.erb
<div class="portlet box yellow" id="expected_and_accomplished">
  <div class="portlet-title">
    <div class="caption"><i class="icon-reorder"></i><%= t('.title') %></div>
    <div class="tools">
      <a href="javascript:;" class="collapse"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="chart"></div>
  </div>
</div>

app/views/reports/_follow_up_not_studied_reason.html.erb
<div class="portlet box yellow" id="follow_up_not_studied_reason">
  <div class="portlet-title">
    <div class="caption"><i class="icon-reorder"></i><%= t('.title') %></div>
    <div class="tools">
      <a href="javascript:;" class="collapse"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="chart"></div>
  </div>
</div>

app/views/reports/_study_hours_evolution.html.erb
<div class="portlet box green" id="study_hours_evolution">
  <div class="portlet-title">
    <div class="caption"><i class="icon-reorder"></i><%= t('.title') %></div>
    <div class="tools">
      <a href="javascript:;" class="collapse"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="chart"></div>
  </div>
</div>

app/views/reports/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <h4 class="show-results-timetable"><%= t('.results_for') %>: &nbsp;&nbsp;&nbsp;</h4>

    <select id="timetable-select" style="width: 45%;" data-url-callback="<%= change_timetable_report_path %>">
      <% current_user.timetables.each do |t| %>
        <option value="<%= t.id %>" <%= 'selected' if @timetable == t %>><%= t.name %></option>
      <% end %>
    </select>
  </div>
</div>
<hr>

<div class="row-fluid">
  <div class="span12">
    <%= render 'study_hours_evolution' %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <%= render 'expected_and_accomplished' %>
  </div>
  <div class="span6">
    <%= render 'follow_up_not_studied_reason' %>
  </div>
</div>